name: Main Action
on: [push]
jobs:
    Main:
        runs-on: ubuntu-latest
        steps:
            - name: Install
              run: yarn install
            - name: Test
              run: yarn test
            - name: ESLint
              run: yarn eslint
            - name: TypeScript
              run: yarn tsc
            - name: Deploy
              run: yarn deploy
