on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

name: Main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: yarn install

            - name: Test
              run: yarn test

            - name: ESLint
              run: yarn eslint

            - name: TypeScript
              run: yarn tsc

            - name: Deploy
              run: yarn deploy
