name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: fusion-engineering/setup-git-credentials@v2
              with:
                  credentials: ${{secrets.GIT_CREDENTIALS}}
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Move to workspace
              run: cd ${{ github.workspace }}
            - name: Install
              run: yarn install
            - name: Create env file
              run: |
                  touch .env
                  echo ${{secrets.PORTFOLIO_ENV}} >> .env
            - name: Deploy
              run: |
                  git config user.name Oscar Serna
                  git config user.email oscr.serna@gmail.com
                  yarn deploy
