name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
            - name: Move to workspace
              run: cd ${{ github.workspace }}
            - name: Install
              run: yarn install
            - name: Deploy
              run: yarn deploy
