name: Main
on: [push]
jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
              run: cd ${{ github.workspace }}
            - name: Install
              run: yarn install
            - name: Test
              run: yarn test
            - name: ESLint
              run: yarn eslint
            - name: TypeScript
              run: yarn tsc
            - name: Deploy
              run: yarn deploy
